#!/bin/bash

if ! command -v docker-compose &>/dev/null; then
  DOCKER=0
else
  DOCKER=1
  if [ ! "$(docker ps -q -f name=db)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=db)" ]; then
      docker-compose down
    fi
    docker-compose up --no-start
    docker-compose start db
  fi
fi

if ! [ -d "./vendor/" ]; then
  echo "Installing dependencies files"
  if [ $DOCKER -eq 1 ]; then
    docker-compose run --rm app composer install
  else
    composer install
  fi
fi

if [ $DOCKER -eq 1 ]; then
  docker-compose run --rm app php src/application.php "$@"
else
  php src/application.php "$@"
fi
